Repository developmentseed/lonboard, pull requests merged in 2025-06, with the labels that each got.

#804 docs: Reword section in "How it works" to reflect GeoParquet 1.1
  docs/how-it-works/index.md
Labels: docs

#736 feat: Reinstate tooltip
  lonboard/_map.py
  lonboard/types/map.py
  src/index.tsx
  src/tooltip/index.css
  src/tooltip/index.ts
Labels: feat

#813 fix: move duckdb imports to inside function
  lonboard/_geoarrow/_duckdb.py
Labels: fix
