Repository developmentseed/lonboard, pull requests merged in 2025-08, with the labels that each got.

#844 ci: Add CI test for Python 3.13
  .github/workflows/test.yml
  pyproject.toml
  uv.lock
Labels: ci

#845 perf: Avoid numpy memory copy when shapely-produced offsets are already `int32`
  lonboard/_geoarrow/extension_types.py
Labels: perf

#851 docs: Update examples referencing '_height'
  examples/air-traffic-control.ipynb
  examples/ais-movingpandas.ipynb
  examples/internet-speeds.ipynb
  examples/map_challenge/1-points.ipynb
  examples/overture-geoparquet.ipynb
Labels: docs

#854 chore: Bump geoarrow-rust dep
  pyproject.toml
  uv.lock
Labels: chore
